# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Uncomment the following line to enable the Sofle OLED Display
CONFIG_ZMK_DISPLAY=y
#CONFIG_ZMK_DISPLAY_SSD1306=y  
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_SYSTEM=y

CONFIG_I2C=y
CONFIG_SSD1306=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n
# Uncomment these two lines to add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment this line below to add rgb underglow / backlight support
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_SPI=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
# 0	Solid color    1 Breathe     2	Spectrum     3	Swirl
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=1
CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=5
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=80
# Turn off RGB underglow when keyboard goes into idle state
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=n

# # Hue step in degrees (0-359) used by RGB actions default 10
# CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=30

# # Brightness step in percent used by RGB actions default 10
CONFIG_ZMK_RGB_UNDERGLOW_SAT_STEP=5
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=345
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=50

# # Animation module
# CONFIG_ZMK_ANIMATION=y

# # Tron lighting conifg
# CONFIG_ZMK_TRON_SNAKE=y
# CONFIG_ZMK_TRON_SNAKE_IDLE_OFF=y

# Uncomment the line below to disable external power toggling by the underglow.
# By default toggling the underglow on and off also toggles external power
# on and off. This also causes the display to turn off.
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

CONFIG_ZMK_POINTING=n

### Battey reporting
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y
CONFIG_ZMK_BATTERY_REPORTING=y
#Peripheral battery level
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y

# Enable ZMK Studio
CONFIG_ZMK_STUDIO=y
# # Disable studio locking
CONFIG_ZMK_STUDIO_LOCKING=n

### Bluetooth 
#Power enhancer
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Give the keyboard a custom name
CONFIG_ZMK_KEYBOARD_NAME="Sofle"

# Soft Off
CONFIG_ZMK_PM_SOFT_OFF=y

# Debounce
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=3
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=3
